spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #properties:
    #hibernate:
    #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
